import { createClient } from '@supabase/supabase-js'
import { NextRequest, NextResponse } from 'next/server'

// Use service role key to bypass RLS
const supabaseAdmin = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL || '',
  process.env.SUPABASE_SERVICE_ROLE_KEY || ''
)

export async function POST(request: NextRequest) {
  try {
    const body = await request.json()
    
    const {
      customerName,
      customerEmail,
      customerPhone,
      shippingAddress,
      shippingCity,
      shippingProvince,
      shippingPostalCode,
      shippingNotes,
      paymentMethod,
      businessOrders,
      userId
    } = body

    // Validate required fields
    if (!customerName || !customerEmail || !shippingAddress || !shippingCity || !businessOrders) {
      return NextResponse.json(
        { error: 'Missing required fields' },
        { status: 400 }
      )
    }

    const createdOrders = []

    // Create an order for each business
    for (const businessOrder of businessOrders) {
      const { businessId, items } = businessOrder

      console.log(`Processing business ${businessId} with ${items.length} items`)
      console.log('Items received:', JSON.stringify(items, null, 2))

      if (!items || items.length === 0) {
        throw new Error(`No items provided for business ${businessId}`)
      }

      // Calculate totals
      const subtotalCents = items.reduce((sum: number, item: any) => {
        const itemPrice = Number(item.price) || 0
        const itemQty = Number(item.quantity) || 1
        return sum + (itemPrice * itemQty)
      }, 0)
      
      const shippingCents = 0 // Free shipping
      const taxCents = Math.round(subtotalCents * 0.15) // 15% VAT
      const totalCents = subtotalCents + shippingCents + taxCents

      console.log(`Order totals - subtotal: ${subtotalCents}, tax: ${taxCents}, total: ${totalCents}`)

      // Create order using service role (bypasses RLS)
      // order_number is auto-generated by the database trigger
      const { data: order, error: orderError } = await supabaseAdmin
        .from('orders')
        .insert({
          business_id: businessId,
          customer_id: userId || null,
          customer_name: customerName,
          customer_email: customerEmail,
          customer_phone: customerPhone || null,
          shipping_address: shippingAddress,
          shipping_city: shippingCity,
          shipping_province: shippingProvince,
          shipping_postal_code: shippingPostalCode,
          shipping_notes: shippingNotes || null,
          subtotal_cents: subtotalCents,
          shipping_cents: shippingCents,
          tax_cents: taxCents,
          total_cents: totalCents,
          currency: 'ZAR',
          payment_method: paymentMethod,
          payment_status: 'pending',
          status: 'pending'
        })
        .select()
        .single()

      if (orderError) {
        console.error('Order creation error:', orderError)
        throw new Error(`Failed to create order: ${orderError.message}`)
      }

      // Create order items
      const orderItems = items.map((item: any) => {
        // Ensure price and quantity are numbers
        const unitPrice = Number(item.price) || 0
        const qty = Number(item.quantity) || 1
        const totalPrice = unitPrice * qty

        if (!item.name) {
          throw new Error('Product name is required for order items')
        }

        if (totalPrice === 0) {
          throw new Error(`Invalid price calculation for ${item.name}: price=${unitPrice}, quantity=${qty}`)
        }

        return {
          order_id: order.id,
          product_id: item.productId || null,
          product_name: item.name,
          product_description: item.description || null,
          product_image_url: item.image || null,
          variant_size: item.variant?.size || null,
          variant_color: item.variant?.color || null,
          variant_options: item.variant?.options || null,
          unit_price_cents: unitPrice,
          quantity: qty,
          total_price_cents: totalPrice,
          subtotal_cents: totalPrice,
          special_instructions: null
        }
      })

      console.log('Order items to insert:', JSON.stringify(orderItems, null, 2))

      const { error: itemsError } = await supabaseAdmin
        .from('order_items')
        .insert(orderItems)

      if (itemsError) {
        console.error('Order items creation error:', itemsError)
        console.error('Items that failed:', JSON.stringify(orderItems, null, 2))
        throw new Error(`Failed to create order items: ${itemsError.message}`)
      }

      createdOrders.push(order)
    }

    return NextResponse.json({
      success: true,
      orders: createdOrders
    })

  } catch (error) {
    console.error('Order creation API error:', error)
    return NextResponse.json(
      { error: error instanceof Error ? error.message : 'Failed to create orders' },
      { status: 500 }
    )
  }
}
