-- Enhanced tagging system with category-specific tags
-- Remove Products/Services from tags and add 100 specific tags for each category

-- First, remove the generic "Products" and "Services" tags
DELETE FROM product_tag_assignments WHERE tag_id IN (
  SELECT id FROM product_tags WHERE name IN ('Products', 'Services')
);
DELETE FROM product_tags WHERE name IN ('Products', 'Services');

-- Add category field to product_tags to organize tags by category
ALTER TABLE product_tags ADD COLUMN IF NOT EXISTS category VARCHAR(20) DEFAULT 'general';

-- Insert 100 PRODUCT-specific tags
INSERT INTO product_tags (name, icon, color, is_system_tag, category) VALUES
-- Food & Beverages (20 tags)
('Organic', '🌱', '#22C55E', true, 'products'),
('Gluten-Free', '🌾', '#F59E0B', true, 'products'),
('Vegan', '🥬', '#10B981', true, 'products'),
('Fresh', '✨', '#06B6D4', true, 'products'),
('Local', '🏠', '#8B5CF6', true, 'products'),
('Artisan', '👨‍🍳', '#F97316', true, 'products'),
('Homemade', '🏡', '#EF4444', true, 'products'),
('Gourmet', '👑', '#A855F7', true, 'products'),
('Healthy', '💚', '#22C55E', true, 'products'),
('Spicy', '🌶️', '#DC2626', true, 'products'),
('Sweet', '🍯', '#F59E0B', true, 'products'),
('Savory', '🧂', '#6B7280', true, 'products'),
('Frozen', '❄️', '#3B82F6', true, 'products'),
('Canned', '🥫', '#F97316', true, 'products'),
('Bottled', '🍾', '#10B981', true, 'products'),
('Imported', '🌍', '#8B5CF6', true, 'products'),
('Premium', '⭐', '#FFD700', true, 'products'),
('Budget', '💰', '#22C55E', true, 'products'),
('Family-Size', '👨‍👩‍👧‍👦', '#F59E0B', true, 'products'),
('Single-Serve', '🍽️', '#06B6D4', true, 'products'),

-- Fashion & Clothing (20 tags)
('Designer', '✨', '#A855F7', true, 'products'),
('Casual', '👕', '#6B7280', true, 'products'),
('Formal', '🤵', '#1F2937', true, 'products'),
('Vintage', '🕰️', '#92400E', true, 'products'),
('Trendy', '🔥', '#EF4444', true, 'products'),
('Comfortable', '☁️', '#06B6D4', true, 'products'),
('Durable', '💪', '#059669', true, 'products'),
('Waterproof', '💧', '#3B82F6', true, 'products'),
('Breathable', '🌬️', '#10B981', true, 'products'),
('Stretchy', '🤸', '#8B5CF6', true, 'products'),
('Cotton', '🌿', '#22C55E', true, 'products'),
('Leather', '🐄', '#92400E', true, 'products'),
('Silk', '🐛', '#F8FAFC', true, 'products'),
('Wool', '🐑', '#F59E0B', true, 'products'),
('Synthetic', '🧪', '#6366F1', true, 'products'),
('Handmade', '✋', '#F97316', true, 'products'),
('Machine-Wash', '🌊', '#06B6D4', true, 'products'),
('Dry-Clean', '🧽', '#8B5CF6', true, 'products'),
('Plus-Size', '➕', '#EC4899', true, 'products'),
('Petite', '📏', '#A855F7', true, 'products'),

-- Electronics & Tech (20 tags)
('Smart', '🧠', '#3B82F6', true, 'products'),
('Wireless', '📶', '#10B981', true, 'products'),
('Bluetooth', '📱', '#06B6D4', true, 'products'),
('USB-C', '🔌', '#6B7280', true, 'products'),
('Fast-Charging', '⚡', '#F59E0B', true, 'products'),
('HD', '📺', '#8B5CF6', true, 'products'),
('4K', '🎬', '#A855F7', true, 'products'),
('Gaming', '🎮', '#EF4444', true, 'products'),
('Professional', '💼', '#1F2937', true, 'products'),
('Portable', '🎒', '#22C55E', true, 'products'),
('Compact', '📦', '#F97316', true, 'products'),
('Energy-Efficient', '🔋', '#10B981', true, 'products'),
('Refurbished', '♻️', '#059669', true, 'products'),
('Brand-New', '✨', '#FFD700', true, 'products'),
('Warranty', '🛡️', '#3B82F6', true, 'products'),
('Touch-Screen', '👆', '#EC4899', true, 'products'),
('Voice-Control', '🎤', '#8B5CF6', true, 'products'),
('Water-Resistant', '💧', '#06B6D4', true, 'products'),
('Shockproof', '🛡️', '#6B7280', true, 'products'),
('Anti-Glare', '🕶️', '#1F2937', true, 'products'),

-- Health & Beauty (20 tags)
('Natural', '🌿', '#22C55E', true, 'products'),
('Chemical-Free', '🚫', '#10B981', true, 'products'),
('Hypoallergenic', '🤧', '#06B6D4', true, 'products'),
('Dermatologist-Tested', '👩‍⚕️', '#3B82F6', true, 'products'),
('Anti-Aging', '⏰', '#A855F7', true, 'products'),
('Moisturizing', '💧', '#06B6D4', true, 'products'),
('SPF', '☀️', '#F59E0B', true, 'products'),
('Fragrance-Free', '🚫', '#6B7280', true, 'products'),
('Cruelty-Free', '🐰', '#EC4899', true, 'products'),
('Paraben-Free', '🚫', '#10B981', true, 'products'),
('Sulfate-Free', '🧴', '#22C55E', true, 'products'),
('Clinically-Proven', '🔬', '#8B5CF6', true, 'products'),
('Fast-Acting', '⚡', '#EF4444', true, 'products'),
('Long-Lasting', '⏳', '#F97316', true, 'products'),
('Travel-Size', '✈️', '#06B6D4', true, 'products'),
('Professional-Grade', '💼', '#1F2937', true, 'products'),
('Sensitive-Skin', '🤲', '#EC4899', true, 'products'),
('All-Natural', '🌱', '#059669', true, 'products'),
('Vitamin-Enriched', '💊', '#F59E0B', true, 'products'),
('Herbal', '🌿', '#22C55E', true, 'products'),

-- Home & Garden (20 tags)
('Eco-Friendly', '♻️', '#22C55E', true, 'products'),
('Biodegradable', '🌱', '#10B981', true, 'products'),
('Non-Toxic', '🚫', '#06B6D4', true, 'products'),
('Dishwasher-Safe', '🍽️', '#3B82F6', true, 'products'),
('Microwave-Safe', '📡', '#F59E0B', true, 'products'),
('Oven-Safe', '🔥', '#EF4444', true, 'products'),
('Freezer-Safe', '❄️', '#06B6D4', true, 'products'),
('BPA-Free', '🚫', '#10B981', true, 'products'),
('Stain-Resistant', '🛡️', '#8B5CF6', true, 'products'),
('Easy-Clean', '🧽', '#22C55E', true, 'products'),
('Space-Saving', '📦', '#F97316', true, 'products'),
('Multi-Purpose', '🔄', '#A855F7', true, 'products'),
('Heavy-Duty', '💪', '#1F2937', true, 'products'),
('Lightweight', '🪶', '#06B6D4', true, 'products'),
('Rust-Proof', '🛡️', '#6B7280', true, 'products'),
('Weather-Resistant', '🌦️', '#3B82F6', true, 'products'),
('Indoor', '🏠', '#F59E0B', true, 'products'),
('Outdoor', '🌳', '#22C55E', true, 'products'),
('Decorative', '🎨', '#EC4899', true, 'products'),
('Functional', '⚙️', '#6B7280', true, 'products')

ON CONFLICT (name) DO NOTHING;

-- Insert 100 SERVICE-specific tags
INSERT INTO product_tags (name, icon, color, is_system_tag, category) VALUES
-- Professional Services (25 tags)
('Certified', '🏆', '#FFD700', true, 'services'),
('Licensed', '📜', '#3B82F6', true, 'services'),
('Insured', '🛡️', '#10B981', true, 'services'),
('Bonded', '🔒', '#6B7280', true, 'services'),
('Experienced', '⭐', '#F59E0B', true, 'services'),
('Expert', '🎯', '#EF4444', true, 'services'),
('Specialist', '🔬', '#8B5CF6', true, 'services'),
('Consultation', '💬', '#06B6D4', true, 'services'),
('Emergency', '🚨', '#DC2626', true, 'services'),
('24/7', '🕐', '#1F2937', true, 'services'),
('Same-Day', '⚡', '#F59E0B', true, 'services'),
('Next-Day', '📅', '#22C55E', true, 'services'),
('Appointment', '📋', '#8B5CF6', true, 'services'),
('Walk-In', '🚶', '#06B6D4', true, 'services'),
('Mobile', '🚐', '#10B981', true, 'services'),
('On-Site', '🏠', '#F97316', true, 'services'),
('Remote', '💻', '#3B82F6', true, 'services'),
('Virtual', '🌐', '#A855F7', true, 'services'),
('In-Person', '👥', '#EC4899', true, 'services'),
('Group', '👨‍👩‍👧‍👦', '#22C55E', true, 'services'),
('Individual', '👤', '#6B7280', true, 'services'),
('Custom', '🎨', '#F97316', true, 'services'),
('Standard', '📏', '#059669', true, 'services'),
('Premium', '👑', '#A855F7', true, 'services'),
('Basic', '📋', '#6B7280', true, 'services'),

-- Health & Wellness Services (25 tags)
('Therapeutic', '💆', '#10B981', true, 'services'),
('Relaxing', '😌', '#06B6D4', true, 'services'),
('Healing', '🌿', '#22C55E', true, 'services'),
('Preventive', '🛡️', '#3B82F6', true, 'services'),
('Diagnostic', '🔍', '#8B5CF6', true, 'services'),
('Treatment', '💊', '#EF4444', true, 'services'),
('Rehabilitation', '🏃', '#F59E0B', true, 'services'),
('Wellness', '🧘', '#10B981', true, 'services'),
('Fitness', '💪', '#DC2626', true, 'services'),
('Nutrition', '🥗', '#22C55E', true, 'services'),
('Mental-Health', '🧠', '#8B5CF6', true, 'services'),
('Stress-Relief', '😮‍💨', '#06B6D4', true, 'services'),
('Pain-Management', '🩹', '#F97316', true, 'services'),
('Holistic', '🌸', '#EC4899', true, 'services'),
('Alternative', '🌿', '#059669', true, 'services'),
('Traditional', '📜', '#92400E', true, 'services'),
('Modern', '🔬', '#3B82F6', true, 'services'),
('Non-Invasive', '🤲', '#10B981', true, 'services'),
('Gentle', '🤗', '#F8FAFC', true, 'services'),
('Intensive', '🔥', '#DC2626', true, 'services'),
('Maintenance', '🔧', '#6B7280', true, 'services'),
('Cosmetic', '💄', '#EC4899', true, 'services'),
('Medical', '🏥', '#EF4444', true, 'services'),
('Pediatric', '👶', '#F59E0B', true, 'services'),
('Senior', '👴', '#8B5CF6', true, 'services'),

-- Business & Tech Services (25 tags)
('Digital', '💻', '#3B82F6', true, 'services'),
('Online', '🌐', '#10B981', true, 'services'),
('Cloud', '☁️', '#06B6D4', true, 'services'),
('AI-Powered', '🤖', '#8B5CF6', true, 'services'),
('Automated', '⚙️', '#6B7280', true, 'services'),
('Manual', '✋', '#F97316', true, 'services'),
('Strategic', '🎯', '#1F2937', true, 'services'),
('Creative', '🎨', '#EC4899', true, 'services'),
('Analytical', '📊', '#059669', true, 'services'),
('Data-Driven', '📈', '#3B82F6', true, 'services'),
('Results-Oriented', '🎯', '#22C55E', true, 'services'),
('ROI-Focused', '💰', '#F59E0B', true, 'services'),
('Scalable', '📈', '#10B981', true, 'services'),
('Flexible', '🤸', '#8B5CF6', true, 'services'),
('Agile', '⚡', '#EF4444', true, 'services'),
('Waterfall', '🌊', '#06B6D4', true, 'services'),
('Lean', '📏', '#22C55E', true, 'services'),
('Full-Service', '🔄', '#A855F7', true, 'services'),
('Specialized', '🎯', '#F97316', true, 'services'),
('Multi-Platform', '📱', '#3B82F6', true, 'services'),
('Cross-Platform', '🔄', '#8B5CF6', true, 'services'),
('Integration', '🔗', '#10B981', true, 'services'),
('Migration', '📦', '#F59E0B', true, 'services'),
('Optimization', '⚡', '#22C55E', true, 'services'),
('Maintenance', '🔧', '#6B7280', true, 'services'),

-- Personal & Lifestyle Services (25 tags)
('Personalized', '👤', '#EC4899', true, 'services'),
('Customized', '🎨', '#A855F7', true, 'services'),
('Bespoke', '✨', '#FFD700', true, 'services'),
('Luxury', '💎', '#8B5CF6', true, 'services'),
('Affordable', '💰', '#22C55E', true, 'services'),
('Budget-Friendly', '🏷️', '#F59E0B', true, 'services'),
('High-End', '👑', '#1F2937', true, 'services'),
('Eco-Friendly', '♻️', '#059669', true, 'services'),
('Sustainable', '🌱', '#10B981', true, 'services'),
('Organic', '🌿', '#22C55E', true, 'services'),
('Local', '🏠', '#F97316', true, 'services'),
('International', '🌍', '#3B82F6', true, 'services'),
('Seasonal', '🍂', '#F59E0B', true, 'services'),
('Year-Round', '📅', '#6B7280', true, 'services'),
('Weekend', '📅', '#8B5CF6', true, 'services'),
('Weekday', '📋', '#06B6D4', true, 'services'),
('Evening', '🌙', '#1F2937', true, 'services'),
('Morning', '🌅', '#F59E0B', true, 'services'),
('Flexible-Hours', '🕐', '#10B981', true, 'services'),
('Fixed-Schedule', '📅', '#6B7280', true, 'services'),
('Pet-Friendly', '🐕', '#EC4899', true, 'services'),
('Child-Friendly', '👶', '#F59E0B', true, 'services'),
('Senior-Friendly', '👴', '#8B5CF6', true, 'services'),
('Accessible', '♿', '#3B82F6', true, 'services'),
('Multilingual', '🗣️', '#A855F7', true, 'services')

ON CONFLICT (name) DO NOTHING;

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_product_tags_category ON product_tags(category);
CREATE INDEX IF NOT EXISTS idx_product_tags_category_system ON product_tags(category, is_system_tag);